{% set name = "smp" %}
{% set version = "0.1.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/smp/archive/v{{ version }}.tar.gz
  sha256: 66fbf6e70a9bdfefadd7d3e98dd3415990d81d629ae333055afeeaabdf3c0761

build:
  number: 1
  noarch: python
  entry_points:
    - python-smp = smp:_main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - SMP
    - smp
  commands:
    - python-smp --help
    - python -m smp test

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  home: https://github.com/IntelPython/smp
  summary: a Static Multi-Processing module managing nested parallelism

extra:
  recipe-maintainers:
    - anton-malakhov
